// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNs02chp4msdZzST9WcG1cYJEwsDapVX4',
    appId: '1:445511638301:web:e938826cfd555ed3c055f4',
    messagingSenderId: '445511638301',
    projectId: 'pstb-dbab8',
    authDomain: 'pstb-dbab8.firebaseapp.com',
    storageBucket: 'pstb-dbab8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe6oEe4FY-s27bL4lwxi1fh0qOeo3zPzE',
    appId: '1:445511638301:android:8216af9a7615ba15c055f4',
    messagingSenderId: '445511638301',
    projectId: 'pstb-dbab8',
    storageBucket: 'pstb-dbab8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgt-XD4tJZIOGmsvmM9Hj7jQW0mZ_XQ0',
    appId: '1:445511638301:ios:aeabb3f069ffefcec055f4',
    messagingSenderId: '445511638301',
    projectId: 'pstb-dbab8',
    storageBucket: 'pstb-dbab8.firebasestorage.app',
    iosBundleId: 'com.example.pstb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgt-XD4tJZIOGmsvmM9Hj7jQW0mZ_XQ0',
    appId: '1:445511638301:ios:aeabb3f069ffefcec055f4',
    messagingSenderId: '445511638301',
    projectId: 'pstb-dbab8',
    storageBucket: 'pstb-dbab8.firebasestorage.app',
    iosBundleId: 'com.example.pstb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNs02chp4msdZzST9WcG1cYJEwsDapVX4',
    appId: '1:445511638301:web:db5e38334341fdbfc055f4',
    messagingSenderId: '445511638301',
    projectId: 'pstb-dbab8',
    authDomain: 'pstb-dbab8.firebaseapp.com',
    storageBucket: 'pstb-dbab8.firebasestorage.app',
  );
}
